services:
  brev-container:
    build: 
      context: https://github.com/Intron7/brev.docker.git # Path where Dockerfile is located
      dockerfile: Dockerfile 
    runtime: nvidia
    container_name: brev-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_HOME=/usr/local/cuda
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64
      - PATH=/opt/venv/bin:/usr/local/cuda/bin:$PATH
      - UV_HTTP_TIMEOUT=120
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
