services:
  rapids:
    image: nvcr.io/nvidia/rapidsai/notebooks:24.12-cuda12.5-py3.12
    container_name: rapids-singlecell-container
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8888:8888"
      - "8787:8787"  # Dask Dashboard (optional)
      - "8786:8786"  # Dask Scheduler (optional)

    command: >
      bash -c "pip install uv && uv pip install --system rapids-singlecell decoupler omnipath wget gdown && jupyter lab --ip='*'' --port=8888 --NotebookApp.token='' --NotebookApp.password=''"

